### PR TITLE
fix: tests respect --strip like binaries (#4103)

### LINKED ISSUE #4103: Expose an option or flag to disable stripping of symbols on `go_test` targets without `--@io_bazel_rules_go//go/config:debug`
As of #2573, builds of `go_test` targets will always result in a binary with its symbols. In #2691, it's reiterated this is working as intended.

This behavior can be disabled with `--@io_bazel_rules_go//go/config:debug`, but that has the additional implication of disabling inlining. So, if you are trying to diagnose a problem or especially debug anything related to performance, this is not an option you realistically have as any investigation you will do will be on a generated binary that is probably substantively different from your production binary.

In the GitHub issues discussing this, it's claimed that this behavior was adopted for a performance benefit. Maybe that is true (I haven't profiled anything using recent versions of `go`, although it's possible the situation has changed in 4 years), but there should be some option that one can apply to disable this stripping where relevant without enabling any other command-line flags that would impact the performance or behavior of the generated binary.

I can see two obvious options:

1. Provide a new flag (e.g. `--@io_bazel-rules_go//go/config:no_strip_tests`). Update the logic [here](https://github.com/bazelbuild/rules_go/blob/ee74d01c799ee3069d59fb76d584e064b3cac852/go/private/rules/test.bzl#L144) to not add `-s -w` if either `debug` or `no_strip_tests` are set, instead of only checking `debug`.
2. Honor `--strip`, i.e. do not strip these binaries if `--strip=never` is set.

Alternatively this stripping behavior could be updated to be opt-in instead of mandatory. It could also be re-evaluated whether this optimization is needed on the latest versions of the Go SDK.

If it's agreed option 1 ("Provide a new flag...") is best, I can submit a PR to that effect.

### PR DESCRIPTION
**Pull request by ajwerner**
**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**

Fixes #4103

### CODE REVIEW

File: tests/core/strip/strip_test.go [hunk 1]
```diff
@@ -259,10 +306,35 @@ var wantStackTrace = []string{
 	`^$`,
 }
 
-func embedWantedStackTraces() string {
+func embedWantedTestStackTrace() string {
+	return embedStringSliceVar("wantTestStackTrace", wantTestStackTrace)
+}
+
+var wantTestStackTrace = []string{
+	`^goroutine \d+ \[running\]:$`,
```
Comment (fmeum) [inline tests/core/strip/strip_test.go:314]: This is very comprehensive, but also somewhat prone to breaking with future versions of Go. Could you pick out one or two lines that are essential for verifying the presence of debug information and drop the rest?

Comment (ajwerner) [reply tests/core/strip/strip_test.go]: Thanks for the review! I changed the testing so that it reuses exactly the previous expectations and doesn't look at the tail that's due to the implementation of go's testing package. See if this pleases.

**Comment by ajwerner** [comment]
@fmeum anything else you want here?

**Review by fmeum — APPROVED** [review]
@linzhp Any concerns from your side?

**Comment by linzhp** [comment]
Fine with me. Sorry for late reply
