### PR TITLE
Revert "Fail when expected files are not produced by protoc (#4287)"

### LINKED ISSUE #4317: go-protoc-bin failed: error executing GoProtocGen command
Hi! I'm the maintainer of the grpc-gateway. It seems that something in v0.54.0 broke our protobuf generation. [This auto-created PR](https://github.com/grpc-ecosystem/grpc-gateway/pull/5472) is failing our bazel build. The error is:

```
 ERROR: /__w/grpc-gateway/grpc-gateway/runtime/internal/examplepb/BUILD.bazel:29:17: Generating into bazel-out/k8-fastbuild/bin/runtime/internal/examplepb/examplepb_go_proto_/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/internal/examplepb failed: (Exit 1): go-protoc-bin failed: error executing GoProtocGen command (from target //runtime/internal/examplepb:examplepb_go_proto) bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/rules_go+/go/tools/builders/go-protoc/go-protoc-bin -protoc bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/protobuf+/protoc -importpath ... (remaining 51 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
2025/04/15 16:46:48 file "bazel-out/k8-fastbuild/bin/runtime/internal/examplepb/examplepb_go_proto_/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/internal/examplepb/example_grpc.pb.go" expected from plugin "bazel-out/k8-opt-exec-ST-d57f47055a04/bin/go_grpc_reset_plugin_/protoc-gen-go-grpc" but not created
ERROR: /__w/grpc-gateway/grpc-gateway/runtime/internal/examplepb/BUILD.bazel:29:17 GoCompilePkg runtime/internal/examplepb/examplepb_go_proto.a failed: (Exit 1): go-protoc-bin failed: error executing GoProtocGen command (from target //runtime/internal/examplepb:examplepb_go_proto) bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/rules_go+/go/tools/builders/go-protoc/go-protoc-bin -protoc bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/protobuf+/protoc -importpath ... (remaining 51 arguments skipped)
```

I found this a bit hard to parse, but I think the salient part is

```
go-protoc-bin failed: error executing GoProtocGen command
```

It doesn't say what exactly failed, though, so not sure how it broke. Here's the full build log: https://github.com/grpc-ecosystem/grpc-gateway/actions/runs/14474740731/job/40597503943?pr=5472. The command was

```shell 
$ bazel test //...
```

### PR DESCRIPTION
**Pull request by linzhp**
**What type of PR is this?**
Bug fix

**What does this PR do? Why is it needed?**
It's common for a `go_proto_library` to include proto files with and without service definitions at the same time. In this case, the gRPC plugins are needed, but some gRPC plugins don't generate the grpc.pb.go files if there is no service definition. 

Partially reverting #4287 to restore the previous behavior of creating an empty file

**Which issues(s) does this PR fix?**

Fixes #4317

**Other notes for review**

### CODE REVIEW

File: go/tools/builders/protoc.go [hunk 1]
```diff
@@ -185,9 +183,15 @@ func run(args []string) error {
 	for _, f := range files {
 		switch {
 		case f.expected && !f.created:
-			return fmt.Errorf("file %q expected from plugin %q but not created", f.path, *plugin)
+			// Some plugins only create output files if the proto source files have
```
Comment (fmeum) [inline go/tools/builders/protoc.go:186]:
```suggestion
			// Some plugins only create output files if the proto source files
```

**Review by fmeum — APPROVED** [review]

**Comment by linzhp** [comment]
cc @r-hang
