### PR TITLE
Pass config to subanalyzers

### LINKED ISSUE #4328: Report Nogo errors on only changed files.
Hi,

Recently i was trying to get Nogo integrated with our existing Repo. One major integration hurdle I faced was,
When running nogo enabled, the bazel build fails on existing linter issues, even on files that the developer has not touched. 

Given we have a large repo and with many services, we wanted to throw lint errors only on changed files.
I made some hacky patch to lint and report issues on only files the author has touched to overcome this. 
So wanted to understand if there's anything on the roadmap to lint only the changes?

### LINKED ISSUE #4329: Nogo: analyzers flags are not passed to subanalyzers
Currently, nogo passes configuration only to top analyzers, skipping the required subanalyzers. 

Why is it a a problem? Some analyzers split the configuration among a few subanalyzers. Good 
example here is nilaway, which documentation explains how to pass some configuration options
to dedicated nilaway_config subanalyzer.  

https://github.com/uber-go/nilaway/wiki/Configuration#bazelnogo 

Example configuration looks like this:

<details>

```
{
  "nilaway_config": {
    "analyzer_flags": {
      "include-pkgs": "go.uber.org",
      "exclude-pkgs": "vendor/",
      "exclude-file-docstrings": "@generated,Code generated by,Autogenerated by"
    }
  },
  "nilaway": {
    "exclude_files": {
      "bazel-out": "this prevents nilaway from outputting diagnostics on intermediate test files"
    },
    "only_files": {
      "my/code/path": "This is the comment for why we want to enable NilAway on this code path"
    }
  },
}
```

</details>

However, as nilaway_config is just subanalyzer, the analyzer flags are never actually set by nogo. 

## Fix

This commit contains relevant fix. Please let me know if should file pull request in current form or
what adjustments are expected. I'd also love some guidance wrt. testing if needed. 
https://github.com/bazel-contrib/rules_go/commit/d9fb0141c4ae526a0be0d20eefc5c61dce6f4d56

### PR DESCRIPTION
**Pull request by grzegorzsn**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Some analyzers require their subanalyzers to be configured. For instance nilaway has dedicated nilaway_config subanalyzer. 

**Which issues(s) does this PR fix?**

Fixes #4329 

**Other notes for review**

### CODE REVIEW

File: tests/core/nogo/custom/flags/flags_test.go [hunk 1]
```diff
@@ -70,27 +70,36 @@ go_library(
...
+	boolSwitch   			 bool
+	stringSwitch 			 string
+	intSwitch    			 int
+	subanalyzerBoolSwitch    bool
 )
 
+var Subanalyzer = &analysis.Analyzer{
+        Name: "flagger_subanalyzer",
+        Run:  subanalyzerRun,
+        Doc:  "Dummy subanalyzer that crashes it's flag is set'",
```
Comment (fmeum) [inline tests/core/nogo/custom/flags/flags_test.go:88]:
```suggestion
        Doc:  "Dummy subanalyzer that crashes if its flag is set'",
```

**Review by fmeum — APPROVED** [review]
