### PR TITLE
Pass large ldflags to cgo via response file instead of env variable.

### LINKED ISSUE #2654: cgo fails when CGO_LDFLAGS too large
### What version of rules_go are you using?

0.19.10

### What version of gazelle are you using?

0.19.0

### What version of Bazel are you using?

3.1.0

### Does this issue reproduce with the latest releases of all the above?

Not sure. Can't build our project with the latest dependencies.

### What operating system and processor architecture are you using?

x86_64 Linux

Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Any other potentially useful information about your toolchain?

N/A

### What did you do?

Attempted a build with a large C++ cgo dependency ([the Envoy proxy](https://github.com/envoyproxy/envoy)).

### What did you expect to see?

Expected the build to succeed.

### What did you see instead?

The following error:

```
INFO: Analyzed target //:gm-proxy (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/cstrahan/go/src/github.com/deciphernow/gm-proxy/bindings/BUILD.bazel:29:1: GoCompilePkg bindings/linux_amd64_debug/go_default_library%/github.com/deciphernow/gm-proxy/bindings.a failed (Exit 1): builder failed: error executing command 
  (cd /home/cstrahan/.cache/bazel/_bazel_cstrahan/0e3896d6d23d3761a1e0a1ef1f9e1eac/sandbox/linux-sandbox/700/execroot/gm_proxy && \
  exec env - \
    CC=/usr/bin/clang-10 \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=linux \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin:/bin \
  bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/k8-dbg/bin/bindings/linux_amd64_debug/go_default_library%/github.com/deciphernow/gm-proxy/bindings.a-0.params')
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox builder failed: error executing command 
  (cd /home/cstrahan/.cache/bazel/_bazel_cstrahan/0e3896d6d23d3761a1e0a1ef1f9e1eac/sandbox/linux-sandbox/700/execroot/gm_proxy && \
  exec env - \
    CC=/usr/bin/clang-10 \
    CGO_ENABLED=1 \
    GOARCH=amd64 \
    GOOS=linux \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=/usr/bin:/bin \
  bazel-out/host/bin/external/go_sdk/builder '-param=bazel-out/k8-dbg/bin/bindings/linux_amd64_debug/go_default_library%/github.com/deciphernow/gm-proxy/bindings.a-0.params')
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: error running subcommand: fork/exec external/go_sdk/pkg/tool/linux_amd64/cgo: argument list too long
Target //:gm-proxy failed to build
INFO: Elapsed time: 1.028s, Critical Path: 0.64s
INFO: 2 processes: 2 linux-sandbox.
FAILED: Build did NOT complete successfully
```

The build fails due to the `CGO_LDFLAGS` environment variable exceeding the hard 128kB limit on Linux. The build fails when invoking `cgo` here:

https://github.com/bazelbuild/rules_go/blob/v0.19.10/go/tools/builders/cgo2.go#L136

Here's what the environ look like up to that point (formatted as a Go literal for convenience of testing):

```go
[]string{"PATH=/usr/bin:/bin", "GOROOT_FINAL=GOROOT", "CC=/usr/bin/clang-10", "GOROOT=external/go_sdk", "CGO_ENABLED=1", "GOARCH=amd64", "GOPATH=", "TMPDIR=/tmp", "GOOS=linux", "CGO_LDFLAGS=-Wl,--whole-archive bazel-out/k8-dbg/bin/bindings/libenvoy_wrappers.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/filters/proto/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/exe/libenvoy_main_common_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/exe/libprocess_wide_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/http2/libnghttp2_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libproto_descriptors_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/cluster/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/endpoint/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/listener/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/route/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/secret/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libhot_restart_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libhot_restarting_child.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libhot_restarting_parent.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libhot_restarting_base.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/config_validation/libserver_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/config_validation/libadmin_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/config_validation/libapi_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/config_validation/libcluster_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/config_validation/libasync_client_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/config_validation/libdispatcher_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/config_validation/libdns_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/thread_local/libthread_local_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/exe/libplatform_impl_lib_posix.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/filesystem/libfilesystem_impl_lib_posix.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/filesystem/libfile_shared_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/http/authn/libfilter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/http/authn/libauthenticator.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/mixerapi_git/libauthentication_policy_config_proto_lib.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/http/mixer/libfilter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/utils/libauthn_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/utils/libfilter_names_lib.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/tcp/forward_downstream_sni/libconfig_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/tcp/forward_downstream_sni/libconfig_proto.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/tcp/forward_downstream_sni/libforward_downstream_sni_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/tcp/mixer/libfilter_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/istio/control/tcp/libcontrol_lib.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/tcp/sni_verifier/libconfig_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/tcp/sni_verifier/libconfig_proto.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/tcp/sni_verifier/libsni_verifier_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/tcp/tcp_cluster_rewrite/libconfig_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/tcp/tcp_cluster_rewrite/libtcp_cluster_rewrite_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/mixerapi_git/libtcp_cluster_rewrite_config_proto_lib.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/envoy/utils/libutils_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/extensions/common/libjson_util.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/wasm/libwasm_vm_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/wasm/null/libnull_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/wasm/null/libnull_vm_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/wasm/v8/libv8_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_googlesource_chromium_v8/libwee8.a bazel-out/k8-dbg/bin/external/istio_proxy/src/istio/control/http/libcontrol_lib.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/istio/authn/libcontext_proto_cc_proto.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/istio_proxy/src/istio/control/libcommon_lib.a bazel-out/k8-dbg/bin/external/istio_proxy/src/istio/quota_config/libconfig_parser_lib.a bazel-out/k8-dbg/bin/external/istio_proxy/src/istio/mixerclient/libmixerclient_lib.a bazel-out/k8-dbg/bin/external/istio_proxy/src/istio/prefetch/libquota_prefetch_lib.a bazel-out/k8-dbg/bin/external/istio_proxy/src/istio/utils/libutils_lib.a bazel-out/k8-dbg/bin/external/istio_proxy/src/istio/utils/libattribute_names_lib.a bazel-out/k8-dbg/bin/external/mixerapi_git/libmixer_client_config_proto_lib.a bazel-out/k8-dbg/bin/external/mixerapi_git/libmixer_api_protos_lib.a bazel-out/k8-dbg/bin/external/envoy_com_github_gogo_protobuf/libgogo_proto.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/liboptions_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libserver_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libactive_raw_udp_listener_config.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libguarddog_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libwatchdog_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/liblistener_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libdrain_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libfilter_chain_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/liblds_api_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libfilter_matcher_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/upstreams/http/generic/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/upstreams/http/generic/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libssl_context_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libworker_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libconnection_handler_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/access_log/libaccess_log_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/api/libapi_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libcontext_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/memory/libheap_shrinker_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/secret/libsecret_manager_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/secret/libsecret_provider_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libthread_local_store_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libhealth_discovery_service_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/health/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/liboverload_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/admin/libadmin_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/admin/libadmin_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/admin/libconfig_tracker_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/admin/liblisteners_handler_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/admin/liblogs_handler_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/admin/libprofiling_handler_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/profiler/libprofiler_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/admin/libruntime_handler_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/admin/libserver_cmd_handler_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/admin/libserver_info_handler_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/admin/libstats_handler_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/admin/libprometheus_stats_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/admin/libutils_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libmutex_tracer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/html/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libconnection_balancer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/tls/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/tls/libssl_socket_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/tls/libcontext_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/tls/private_key/libprivate_key_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/tls/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/access_loggers/file/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/access_loggers/file/libfile_access_log_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/access_loggers/file/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/access_loggers/grpc/libhttp_config.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/access_loggers/grpc/libhttp_grpc_access_log_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/access_loggers/grpc/libtcp_config.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/access_loggers/grpc/libconfig_utils.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/access_loggers/grpc/libgrpc_access_log_proto_descriptors_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/access_loggers/grpc/libtcp_grpc_access_log_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/access_loggers/grpc/libgrpc_access_log_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/access_loggers/common/libaccess_log_base.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/accesslog/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/accesslog/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/access_loggers/grpc/libgrpc_access_log_utils.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/data/accesslog/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/data/accesslog/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/access_loggers/grpc/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/accesslog/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/clusters/aggregate/libcluster.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/clusters/aggregate/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/cluster/aggregate/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/clusters/dynamic_forward_proxy/libcluster.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/clusters/dynamic_forward_proxy/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/cluster/dynamic_forward_proxy/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/clusters/redis/libredis_cluster.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/singleton/libmanager_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/cluster/redis/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/compression/gzip/compressor/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/compression/gzip/compressor/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/compression/gzip/decompressor/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/compression/gzip/decompressor/libzlib_decompressor_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/compression/gzip/decompressor/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/grpc_credentials/file_based_metadata/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/grpc_credentials/aws_iam/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/aws/libregion_provider_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/grpc_credential/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/grpc_credential/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/health_checkers/redis/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/health_checkers/redis/libredis.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/health_checker/redis/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/adaptive_concurrency/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/adaptive_concurrency/libadaptive_concurrency_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/adaptive_concurrency/controller/libcontroller_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/event/libdispatcher_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/event/libreal_time_system_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/filesystem/libwatcher_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libconnection_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libconnection_base_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libfilter_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libdns_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/liblistener_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/event/liblibevent_scheduler_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/event/libschedulable_cb_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/event/libtimer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/event/libevent_impl_base_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/adaptive_concurrency/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/adaptive_concurrency/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/admission_control/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/admission_control/libadmission_control_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/admission_control/evaluators/libresponse_evaluator_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/admission_control/v3alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/aws_lambda/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/aws_lambda/libaws_lambda_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/aws_lambda/librequest_response_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/aws_lambda/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/aws_lambda/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/aws_request_signing/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/aws_request_signing/libaws_request_signing_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/aws/libcredentials_provider_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/aws/libsigner_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/aws/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/aws_request_signing/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/aws_request_signing/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/buffer/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/buffer/libbuffer_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/buffer/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/buffer/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/cache/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/cache/libcache_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/cache/libcache_filter_utils_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/compressor/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/compressor/libcompressor_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/cors/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/cors/libcors_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/cors/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/cors/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/csrf/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/csrf/libcsrf_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/csrf/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/csrf/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/decompressor/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/decompressor/libdecompressor_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/decompressor/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/dynamic_forward_proxy/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/dynamic_forward_proxy/libproxy_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/dynamic_forward_proxy/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/dynamic_forward_proxy/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/dynamo/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/dynamo/libdynamo_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/dynamo/libdynamo_stats_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/dynamo/libdynamo_request_parser_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/dynamo/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/dynamo/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/ext_authz/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/ext_authz/libext_authz.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/ext_authz/libext_authz_http_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/ext_authz/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/ext_authz/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/fault/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/fault/libfault_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/grpc_http1_bridge/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/grpc_http1_bridge/libhttp1_bridge_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/grpc_http1_bridge/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/grpc_http1_bridge/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/grpc_http1_reverse_bridge/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/grpc_http1_reverse_bridge/libfilter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/grpc_http1_reverse_bridge/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/grpc_http1_reverse_bridge/v2alpha1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/grpc_json_transcoder/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/grpc_json_transcoder/libjson_transcoder_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/grpc_json_transcoder/libhttp_body_utils_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/grpc_json_transcoder/libtranscoder_input_stream_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/grpc_httpjson_transcoding/src/libjson_request_translator.a bazel-out/k8-dbg/bin/external/grpc_httpjson_transcoding/src/librequest_stream_translator.a bazel-out/k8-dbg/bin/external/grpc_httpjson_transcoding/src/librequest_message_translator.a bazel-out/k8-dbg/bin/external/grpc_httpjson_transcoding/src/libprefix_writer.a bazel-out/k8-dbg/bin/external/grpc_httpjson_transcoding/src/librequest_weaver.a bazel-out/k8-dbg/bin/external/grpc_httpjson_transcoding/src/libpath_matcher.a bazel-out/k8-dbg/bin/external/grpc_httpjson_transcoding/src/libhttp_template.a bazel-out/k8-dbg/bin/external/grpc_httpjson_transcoding/src/libresponse_to_json_translator.a bazel-out/k8-dbg/bin/external/grpc_httpjson_transcoding/src/libmessage_reader.a bazel-out/k8-dbg/bin/external/grpc_httpjson_transcoding/src/libmessage_stream.a bazel-out/k8-dbg/bin/external/grpc_httpjson_transcoding/src/libtype_helper.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/grpc_json_transcoder/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/transcoder/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/grpc_stats/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/grpc_stats/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/grpc_stats/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/grpc_web/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/grpc_web/libgrpc_web_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/grpc_web/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/grpc_web/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/gzip/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/gzip/libgzip_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/compression/gzip/compressor/libcompressor_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/compression/gzip/common/libzlib_base_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/common/compressor/libcompressor_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/gzip/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/gzip/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/compressor/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/compressor/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/header_to_metadata/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/header_to_metadata/libheader_to_metadata_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/header_to_metadata/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/header_to_metadata/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/health_check/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/health_check/libhealth_check_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/health_check/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/health_check/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/ip_tagging/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/ip_tagging/libip_tagging_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/ip_tagging/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/ip_tagging/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/jwt_authn/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/jwt_authn/libfilter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/jwt_authn/libfilter_config_interface.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/jwt_authn/libmatchers_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/jwt_authn/libverifier_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/jwt_authn/libauthenticator_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/jwt_authn/libjwks_cache_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/common/libjwks_fetcher_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/jwt_authn/libextractor_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_github_google_jwt_verify/libjwt_verify_lib.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/jwt_authn/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/jwt_authn/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/lua/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/lua/liblua_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/lua/libwrappers_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/crypto/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/lua/libwrappers_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/lua/liblua_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/envoy/bazel/foreign_cc/luajit/lib/libluajit-5.1.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/lua/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/lua/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/on_demand/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/on_demand/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/original_src/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/original_src/liboriginal_src_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/original_src/libconfig_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/original_src/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/original_src/v2alpha1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/ratelimit/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/ratelimit/libratelimit_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/ratelimit/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/rate_limit/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/rbac/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/rbac/librbac_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/rbac/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/rbac/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/router/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/on_demand/libon_demand_update_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/squash/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/squash/libsquash_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/squash/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/squash/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/tap/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/tap/libtap_config_impl.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/tap/libtap_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/tap/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/tap/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/listener/http_inspector/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/listener/http_inspector/libhttp_inspector_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/listener/http_inspector/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/listener/http_inspector/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/listener/original_dst/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/listener/original_dst/liboriginal_dst_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/listener/original_dst/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/listener/original_dst/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/listener/original_src/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/listener/original_src/liboriginal_src_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/listener/original_src/libconfig_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/original_src/libsocket_option_factory_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/original_src/liboriginal_src_socket_option_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/listener/original_src/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/listener/original_src/v2alpha1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/listener/proxy_protocol/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/listener/proxy_protocol/libproxy_protocol_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/listener/proxy_protocol/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/listener/proxy_protocol/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/listener/tls_inspector/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/listener/tls_inspector/libtls_inspector_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/listener/tls_inspector/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/listener/tls_inspector/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/client_ssl_auth/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/client_ssl_auth/libclient_ssl_auth.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/client_ssl_auth/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/client_ssl_auth/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/direct_response/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/direct_response/libfilter.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/direct_response/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/direct_response/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/libconn_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/libdecoder_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/libdubbo_hessian2_serializer_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/libhessian_utils_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/libdubbo_protocol_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/libheartbeat_response_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/router/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/dubbo_proxy/router/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/dubbo/router/v2alpha1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/router/libroute_matcher.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/router/librouter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/libapp_exception_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/libbuffer_helper_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/dubbo_proxy/libserializer_interface.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/dubbo_proxy/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/dubbo_proxy/v2alpha1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/echo/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/echo/libecho.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/echo/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/echo/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/ext_authz/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/ext_authz/libext_authz.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/ext_authz/libext_authz_grpc_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/ext_authz/libcheck_request_utils_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/auth/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/auth/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/auth/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/ext_authz/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/ext_authz/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/http_connection_manager/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libconn_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libdate_provider_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libuser_agent_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/local_reply/liblocal_reply_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/formatter/libsubstitution_format_string_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libscoped_rds_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/librds_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libvhds_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libroute_config_update_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libscoped_config_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/tracing/libhttp_tracer_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/kafka/libkafka_broker_config_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/kafka/libkafka_broker_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/kafka/libkafka_request_codec_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/kafka/libkafka_request_parser_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/kafka/libkafka_response_codec_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/kafka/libkafka_response_parser_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/kafka/libserialization_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/kafka_broker/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/kafka_broker/v2alpha1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/local_ratelimit/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/local_ratelimit/liblocal_ratelimit_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/local_ratelimit/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/local_rate_limit/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/mongo_proxy/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/mongo_proxy/libproxy_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/mongo_proxy/libcodec_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/mongo_proxy/libbson_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/mongo_proxy/libmongo_stats_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/mongo_proxy/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/fault/libfault_config_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/fault/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/fault/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/mongo_proxy/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/mongo_proxy/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/common/fault/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/fault/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/mysql_proxy/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/mysql_proxy/libproxy_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/sqlutils/libsqlutils_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_github_envoyproxy_sqlparser/libsqlparser.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/mysql_proxy/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/mysql_proxy/v1alpha1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/postgres_proxy/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/postgres_proxy/libfilter.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/postgres_proxy/v3alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/ratelimit/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/ratelimit/libratelimit_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/ratelimit/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/rate_limit/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/rbac/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/rbac/librbac_filter.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/rbac/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/rbac/libengine_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/rbac/libmatchers_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/expr/libevaluator_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/expr/libcontext_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/public/libbuiltin_func_registrar.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/public/libcel_function_adapter.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/public/libcel_expr_builder_factory.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/compiler/libflat_expr_builder.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/compiler/libconstant_folding.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libcomprehension_step.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libconst_value_step.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libcontainer_access_step.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libcreate_list_step.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libcreate_struct_step.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libcontainer_backed_map_impl.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libfunction_step.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libexpression_build_warning.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libident_step.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libjump_step.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/liblogic_step.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libselect_step.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libevaluator_core.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libunknowns_utility.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libattribute_trail.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/public/libunknown_function_result_set.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/public/libset_util.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libfield_backed_list_impl.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libfield_backed_map_impl.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/eval/libfield_access.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/public/libast_traverse.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/public/libsource_position.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/public/libcel_function_registry.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/public/libcel_function_provider.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/public/libactivation.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/public/libcel_function.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/eval/public/libcel_value.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/base/libstatusor.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/internal/libproto_util.a bazel-out/k8-dbg/bin/external/com_google_cel_cpp/internal/libstatus_util.a bazel-out/k8-dbg/bin/external/com_google_googleapis/google/rpc/libcode_proto.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/rbac/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/rbac/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/rbac/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/rbac/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_google_googleapis/google/api/expr/v1alpha1/libsyntax_proto.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/redis_proxy/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/redis/libcluster_refresh_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/redis_proxy/libcommand_splitter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/redis_proxy/libproxy_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/redis_proxy/librouter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/redis_proxy/libconn_pool_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/clusters/redis/libredis_cluster_lb.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/clusters/redis/libcrc16_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/common/redis/libclient_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/common/redis/libredis_command_stats_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/common/redis/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/common/redis/libcodec_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/redis_proxy/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/redis_proxy/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/rocketmq_proxy/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/rocketmq_proxy/router/libroute_matcher.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/rocketmq_proxy/router/librouter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/rocketmq_proxy/libconn_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/rocketmq_proxy/libcodec_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/rocketmq_proxy/libprotocol_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/rocketmq_proxy/librocketmq_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/rocketmq_proxy/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/tcp_proxy/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libauto_protocol_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libauto_transport_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libcompact_protocol_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libframed_transport_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libheader_transport_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libtwitter_protocol_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libbinary_protocol_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libthrift_object_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libunframed_transport_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/sni_cluster/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/sni_cluster/libsni_cluster.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/sni_cluster/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/sni_cluster/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/sni_dynamic_forward_proxy/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/sni_dynamic_forward_proxy/libproxy_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/tcp_proxy/libtcp_proxy.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libcidr_range_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libhash_policy_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/tcp_proxy/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/tcp_proxy/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/dynamic_forward_proxy/libdns_cache_manager_impl.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/dynamic_forward_proxy/libdns_cache_impl.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/dynamic_forward_proxy/libdns_cache_resource_manager.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/sni_dynamic_forward_proxy/v3alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/common/dynamic_forward_proxy/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/common/dynamic_forward_proxy/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/zookeeper_proxy/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/zookeeper_proxy/libproxy_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/zookeeper_proxy/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/zookeeper_proxy/v1alpha1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/udp/dns_filter/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/udp/dns_filter/libdns_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libconfig_provider_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libcluster_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libcds_api_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libload_stats_reporter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/load_stats/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/load_stats/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libsubset_lb_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libmaglev_lb_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libring_hash_lb_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libthread_aware_lb_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/grpc/libasync_client_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/http1/libconn_pool_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/http2/libconn_pool_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libshadow_writer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/tcp/libconn_pool_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libconn_pool_base_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/conn_pool/libconn_pool_base_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libupstream_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libeds_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/liblogical_dns_cluster_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/liblogical_host_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/liboriginal_dst_cluster_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libcluster_factory_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libhealth_checker_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libhealth_checker_base_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libcodec_client_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/http1/libcodec_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/http1/libheader_formatter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/third_party/statusor/libstatusor_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/http2/libcodec_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/http2/libmetadata_decoder_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/http2/libmetadata_encoder_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libhost_utility_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/src/proto/grpc/health/v1/lib_health_proto_only.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libstatic_cluster_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libstrict_dns_cluster_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libsubscription_factory_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libfilesystem_subscription_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libgrpc_subscription_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libgrpc_mux_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libhttp_subscription_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/librest_api_fetcher_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libnew_grpc_mux_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libdelta_subscription_state_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libtoken_bucket_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libpausable_ack_queue_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libwatch_map_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/memory/libutils_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libtype_to_endpoint_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libtransport_socket_match_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/liboutlier_detection_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libisolated_store_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libscope_prefixer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libsymbol_table_creator_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libtag_utility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/liballocator_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libstat_merger_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/udp/dns_filter/v3alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/data/dns/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/data/dns/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/udp/udp_proxy/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/udp/udp_proxy/libudp_proxy_filter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/udp/udp_proxy/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/udp/udp_proxy/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/resource_monitors/fixed_heap/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/resource_monitors/fixed_heap/libfixed_heap_monitor.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/memory/libstats_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/envoy/bazel/foreign_cc/gperftools_build/lib/libtcmalloc_and_profiler.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/resource_monitor/fixed_heap/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/resource_monitors/injected_resource/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/resource_monitors/injected_resource/libinjected_resource_monitor.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/resource_monitor/injected_resource/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/stat_sinks/dog_statsd/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/stat_sinks/hystrix/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/stat_sinks/hystrix/libhystrix_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/stat_sinks/metrics_service/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/stat_sinks/metrics_service/libmetrics_proto_descriptors_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/stat_sinks/metrics_service/libmetrics_service_grpc_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/grpc/libasync_client_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/metrics/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/metrics/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/prometheus_metrics_model/libclient_model_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/stat_sinks/statsd/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/stat_sinks/common/statsd/libstatsd_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libconfiguration_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/server/libhot_restart_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libruntime_utility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libresolver_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libsocket_option_factory_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libaddr_family_aware_socket_option_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libsocket_option_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/liblisten_socket_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/router/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/router/librouter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/router/librouter_ratelimit_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libconn_manager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libdecoder_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libtimespan_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_google_absl/absl/types/libbad_any_cast_impl.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/thrift_proxy/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/thrift_proxy/v2alpha1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/thrift/router/v2alpha1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/filters/ratelimit/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/filters/ratelimit/libratelimit_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libapp_exception_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/common/ratelimit/libratelimit_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/ratelimit/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/common/ratelimit/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/ratelimit/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/api/v2/ratelimit/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/network/thrift_proxy/libbuffer_helper_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/thrift_proxy/filters/ratelimit/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/thrift/rate_limit/v2alpha1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/ratelimit/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/ratelimit/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/dynamic_ot/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/dynamic_ot/libdynamic_opentracing_driver_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/lightstep/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/lightstep/liblightstep_tracer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/libbinary_carrier_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/libtracer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/platform/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/recorder/libauto_recorder_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/recorder/liblegacy_manual_recorder_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/recorder/libreport_builder_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/recorder/libmanual_recorder_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/libreport_request_framing_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/recorder/libmetrics_tracker_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/recorder/serialization/libreport_request_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/libbuffer_chain_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/recorder/serialization/libreport_request_header_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/recorder/serialization/libembedded_metrics_message_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/libprotobuf_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/recorder/libfork_aware_recorder_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/legacy/liblegacy_tracer_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/legacy/liblightstep_span_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/libtracer_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/librandom_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/platform/libfork_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/libimmutable_span_context_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/liblightstep_span_context_interface.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/propagation/libpropagation_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/propagation/libpropagation_options_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/propagation/libb3_propagator_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/propagation/liblightstep_propagator_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/propagation/libmultiheader_propagator_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/propagation/libenvoy_propagator_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/3rd_party/base64/libbase64_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/propagation/libbinary_propagation_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/libin_memory_stream_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/lightstep-tracer-common/liblightstep_carrier_proto.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/propagation/libtrace_context_propagator_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/propagation/libbaggage_propagator_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/propagation/libtrace_context_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/libserialization_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/libserialization_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/libhex_conversion_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/libtag_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/recorder/libtransporter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/tracer/libno_default_ssl_roots_pem_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/recorder/libno_grpc_transporter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/recorder/libno_stream_recorder_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/liblogger_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/libchained_stream_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/libcomposable_fragment_input_stream_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/libfragment_input_stream_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/src/common/libtimestamp_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_lightstep_tracer_cpp/lightstep-tracer-common/libcollector_proto.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/datadog/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/datadog/libdatadog_tracer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libversion_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/common/ot/libopentracing_driver_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_github_datadog_dd_opentracing_cpp/libdd_opentracing_cpp.a bazel-out/k8-dbg/bin/external/com_github_msgpack_msgpack_c/libmsgpack.a bazel-out/k8-dbg/bin/external/io_opentracing_cpp/libopentracing.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/zipkin/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/zipkin/libzipkin_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libasync_client_utility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libcluster_update_tracker_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_github_openzipkin_zipkinapi/libzipkin_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/opencensus/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/opencensus/libopencensus_tracer_impl.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/grpc/libgoogle_async_client_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/grpc/libgoogle_grpc_utils_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/grpc/libgoogle_grpc_creds_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/grpc/libtyped_async_client_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/grpc/libcodec_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/grpc/libcontext_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/grpc/libstat_names_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libasync_client_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/trace/libb3.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/trace/libgrpc_trace_bin.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/exporters/trace/ocagent/libocagent_exporter.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/common/internal/libhostname.a bazel-out/k8-dbg/bin/external/opencensus_proto/opencensus/proto/agent/trace/v1/libtrace_service_grpc_cc.a bazel-out/k8-dbg/bin/external/opencensus_proto/opencensus/proto/agent/trace/v1/libtrace_service_proto.a bazel-out/k8-dbg/bin/external/opencensus_proto/opencensus/proto/agent/common/v1/libcommon_proto.a bazel-out/k8-dbg/bin/external/opencensus_proto/opencensus/proto/trace/v1/libtrace_proto.a bazel-out/k8-dbg/bin/external/opencensus_proto/opencensus/proto/resource/v1/libresource_proto.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/exporters/trace/stdout/libstdout_exporter.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/exporters/trace/stackdriver/libstackdriver_exporter.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/common/internal/libtimestamp.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/common/internal/grpc/libstatus.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/common/internal/grpc/libwith_user_agent.a bazel-out/k8-dbg/bin/external/com_google_googleapis/google/devtools/cloudtrace/v2/libcloudtrace_cc_grpc.a bazel-out/k8-dbg/bin/external/com_google_googleapis/google/devtools/cloudtrace/v2/libcloudtrace_proto.a bazel-out/k8-dbg/bin/external/com_google_googleapis/google/api/libclient_proto.a bazel-out/k8-dbg/bin/external/com_google_googleapis/google/api/libfield_behavior_proto.a bazel-out/k8-dbg/bin/external/com_google_googleapis/google/api/libresource_proto.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/exporters/trace/zipkin/libzipkin_exporter.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/trace/libtrace.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/trace/libcloud_trace_context.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/trace/libtrace_context.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/trace/libspan_context.a bazel-out/k8-dbg/bin/external/io_opencensus_cpp/opencensus/common/internal/librandom_lib.a bazel-out/k8-dbg/bin/external/envoy/bazel/foreign_cc/curl/lib/libcurl.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/xray/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/xray/libxray_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/tracers/xray/libdaemon_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/alts/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/alts/libtsi_socket.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/alts/libtsi_frame_protector.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/alts/libtsi_handshaker.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/grpc/libgoogle_grpc_context_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc++.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc++_base.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libcensus.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_lb_policy_pick_first.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_lb_policy_round_robin.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_client_idle_filter.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_max_age_filter.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_message_size_filter.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_resolver_dns_ares.a bazel-out/k8-dbg/bin/external/envoy/bazel/foreign_cc/ares/lib/libcares.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/third_party/address_sorting/libaddress_sorting.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_resolver_dns_native.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_resolver_dns_selection.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_resolver_sockaddr.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_transport_chttp2_server_insecure.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_transport_inproc.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_workaround_cronet_compression_filter.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_server_backward_compatibility.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_lb_policy_grpclb_secure.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_lb_upb.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_resolver_fake.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_lb_policy_xds_secure.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_resolver_xds_secure.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_xds_client_secure.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libenvoy_ads_upb.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libenvoy_core_upb.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libenvoy_type_upb.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_transport_chttp2_client_secure.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_transport_chttp2_server_secure.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_secure.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libtsi.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libalts_frame_protector.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libalts_util.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libalts_upb.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_transport_chttp2_client_insecure.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_transport_chttp2_client_connector.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_client_channel.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libenvoy_orca_upb.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libproto_gen_validate_upb.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgoogle_api_upb.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_client_authority_filter.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_deadline_filter.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libtsi_interface.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_transport_chttp2_server.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_transport_chttp2.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_http_filters.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_base.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_base_c.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_trace.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_transport_chttp2_alpn.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgpr_base.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc_health_upb.a bazel-out/k8-dbg/bin/external/upb/libupb.a bazel-out/k8-dbg/bin/external/com_github_grpc_grpc/libgrpc++_codegen_base_src.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/transport_sockets/alts/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/transport_socket/alts/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/raw_buffer/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libraw_buffer_socket_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/transport_socket/raw_buffer/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/tap/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/tap/libtap_config_impl.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/tap/libtap_config_base.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/tap/libtap_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/tap/libextension_config_base.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/tap/libadmin.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/tap/libtap_matcher.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/data/tap/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/transport_sockets/tap/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/transport_socket/tap/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/common/tap/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/common/tap/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/quic_listeners/quiche/libquic_transport_socket_factory_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/transport_sockets/tls/libcontext_config_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/secret/libsds_api_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/ssl/libcertificate_validation_context_config_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/ssl/libtls_certificate_config_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libdatasource_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libremote_data_fetcher_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/transport_sockets/quic/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/retry/host/previous_hosts/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/retry/previous_hosts/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/retry/host/omit_canary_hosts/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/retry/omit_canary_hosts/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/retry/host/omit_host_metadata/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/retry/host/omit_host_metadata/libomit_host_metadata_predicate_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/retry/host/omit_host_metadata/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/retry/omit_host_metadata/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/retry/priority/previous_priorities/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/retry/priority/previous_priorities/libprevious_priorities_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/retry/previous_priorities/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/cache/simple_http_cache/libsimple_http_cache_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/cache/simple_http_cache/libconfig_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/cache/libhttp_cache_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/cache/libhttp_cache_utils_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/filters/http/cache/libkey_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/cache/v3alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/cache/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/internal_redirect/allow_listed_routes/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/internal_redirect/allow_listed_routes/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/internal_redirect/previous_routes/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/internal_redirect/previous_routes/libprevious_routes_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/internal_redirect/previous_routes/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/internal_redirect/safe_cross_scheme/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/internal_redirect/safe_cross_scheme/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/upstreams/http/http/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/upstreams/http/http/libupstream_request_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/upstreams/http/http/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/upstreams/http/tcp/libconfig.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/upstreams/http/tcp/libupstream_request_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/librouter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libconfig_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libmetadatamatchcriteria_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/librouter_ratelimit_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libconfig_utility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libtls_context_match_criteria_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libhash_policy_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libdebug_config_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libheader_parser_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libheader_formatter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/router/libretry_state_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/access_log/libaccess_log_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/buffer/libwatermark_buffer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libtransport_socket_options_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libapplication_protocol_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libupstream_server_name_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libupstream_subject_alt_names_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stream_info/libfilter_state_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/librequest_id_extension_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libbackoff_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libhex_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libhistogram_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_github_circonus_labs_libcircllhist/liblibcircllhist.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libmetric_impl_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libstats_matcher_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libtag_producer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libtag_extractor_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libperf_annotation_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libwell_known_names.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_github_cncf_udpa/udpa/type/v1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/runtime/libruntime_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/filesystem/libdirectory_iterator_impl_lib_posix.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/init/libmanager_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/init/libtarget_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/init/libwatcher_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/runtime/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/network/http_connection_manager/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/network/http_connection_manager/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/tracing/libhttp_tracer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/formatter/libsubstitution_formatter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/grpc/libcommon_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/data/core/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/data/core/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/buffer/libzero_copy_input_stream_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libbase64_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libheader_utility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/runtime/libruntime_features_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libcodes_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libheader_map_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/grpc/libstatus_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libsocket_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/buffer/libbuffer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/event/liblibevent_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/envoy/bazel/foreign_cc/event/lib/libevent.a bazel-out/k8-dbg/bin/external/envoy/bazel/foreign_cc/event/lib/libevent_pthreads.a bazel-out/k8-dbg/bin/external/envoy/bazel/foreign_cc/event/lib/libevent_core.a bazel-out/k8-dbg/bin/external/com_github_nodejs_http_parser/libhttp_parser.a bazel-out/k8-dbg/bin/external/envoy/bazel/foreign_cc/nghttp2/lib/libnghttp2.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/json/libjson_loader_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stream_info/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/filters/http/router/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/http/router/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/upstream/libload_balancer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/discovery/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/discovery/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libstatus_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_google_absl/absl/status/libstatus.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libmatchers_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libregex_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/libsymbol_table_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/stats/librecent_lookups_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libthread_impl_lib_posix.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libmetadata_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libthread_synchronizer_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/http/libpath_utility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/chromium_url/libchromium_url.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/boringssl/libssl.a bazel-out/k8-dbg/bin/external/boringssl/libcrypto.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/protobuf/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/protobuf/libmessage_validator_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/liblogger_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/admin/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/admin/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/bootstrap/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/bootstrap/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/listener/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/accesslog/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/metrics/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/metrics/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/overload/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/overload/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/trace/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/trace/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/trace/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/opencensus_proto/opencensus/proto/trace/v1/libtrace_config_proto.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/tap/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/route/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/type/tracing/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/type/metadata/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/service/tap/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/data/tap/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libversion_converter_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/config/libapi_type_oracle_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/protobuf/libvisitor_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/envoy/bazel/foreign_cc/yaml/lib/libyaml-cpp.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/cluster/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/endpoint/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/api/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/api/v2/cluster/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/api/v2/listener/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/filter/accesslog/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/api/v2/route/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/type/tracing/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/type/metadata/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/listener/v2/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/api/v2/endpoint/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/transport_sockets/tls/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/api/v2/auth/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/extensions/common/proxy_protocol/libproxy_protocol_header_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/data/cluster/v2alpha/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libaddress_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/network/libio_socket_error_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/api/libos_sys_calls_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libutility_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libassert_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libminimal_logger_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libbase_logger_lib.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy/source/common/common/libhash_lib.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_github_cyan4973_xxhash/libxxhash.a -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/config/core/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/api/v2/core/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/type/matcher/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/type/matcher/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/annotations/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/type/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/type/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_github_cncf_udpa/udpa/core/v1/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/envoy_api/envoy/extensions/upstreams/http/tcp/v3/libpkg_cc_proto.lo -Wl,--no-whole-archive -Wl,--whole-archive bazel-out/k8-dbg/bin/external/com_github_cncf_udpa/udpa/annotations/libpkg_cc_proto.lo -Wl,--no-whole-archive bazel-out/k8-dbg/bin/external/com_google_googleapis/google/api/libhttpbody_proto.a bazel-out/k8-dbg/bin/external/com_google_googleapis/google/api/libannotations_proto.a bazel-out/k8-dbg/bin/external/com_google_googleapis/google/api/libhttp_proto.a bazel-out/k8-dbg/bin/external/com_google_googleapis/google/rpc/libstatus_proto.a bazel-out/k8-dbg/bin/external/com_envoyproxy_protoc_gen_validate/validate/libvalidate_proto.a bazel-out/k8-dbg/bin/external/com_google_protobuf/libprotobuf.a bazel-out/k8-dbg/bin/external/com_google_protobuf/libprotobuf_lite.a bazel-out/k8-dbg/bin/external/envoy/bazel/foreign_cc/zlib/lib/libz.a bazel-out/k8-dbg/bin/external/com_googlesource_code_re2/libre2.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/hash/libhash.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/hash/libcity.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/types/libbad_variant_access.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/strings/libcord.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/strings/libstr_format_internal.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/container/libraw_hash_set.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/types/libbad_optional_access.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/container/libhashtablez_sampler.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/base/libexponential_biased.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/synchronization/libsynchronization.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/synchronization/libgraphcycles_internal.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/debugging/libstacktrace.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/debugging/libsymbolize.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/debugging/libdebugging_internal.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/debugging/libdemangle_internal.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/base/libmalloc_internal.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/time/libtime.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/time/internal/cctz/libtime_zone.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/time/internal/cctz/libcivil_time.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/strings/libstrings.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/strings/libinternal.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/base/libbase.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/base/libdynamic_annotations.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/base/libspinlock_wait.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/base/libthrow_delegate.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/base/libraw_logging_internal.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/base/liblog_severity.a bazel-out/k8-dbg/bin/external/com_google_absl/absl/numeric/libint128.a -fuse-ld=/usr/bin/ld.gold -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -lm -l:libstdc++.a -lrt -ldl -static-libstdc++ -static-libgcc -lpthread -pthread -ldl -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -lpthread -lpthread -lm -lpthread -lm -pthread -pthread -pthread -pthread -pthread"}
```

### PR DESCRIPTION
**Pull request by dgoel**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Pass ldflags to cgo tool via a response file instead of `CGO_LDFLAGS` env variable for go 1.23+. This avoids the "argument list too long" error, which can happen if `CGO_LDFLAGS` is so large that it exceeds the system limits.

Support to accept ldflags via file was added to `go` more than a year ago. References:
- https://go-review.googlesource.com/c/go/+/584655
- Discussion: https://github.com/golang/go/issues/66456

**Which issues(s) does this PR fix?**

Fixes #2654

### CODE REVIEW

**Comment by dgoel** [comment]
> Nit: The indentation look off. Note that golang uses tabs for indentation.

Done! Thanks for pointing out.

File: go/tools/builders/cgo2.go [hunk 1]
```diff
@@ -95,7 +95,21 @@ func cgo2(goenv *env, goSrcs, cgoSrcs, cSrcs, cxxSrcs, objcSrcs, objcxxSrcs, sSr
 		}
 	}
 	combinedLdFlags = append(combinedLdFlags, defaultLdFlags()...)
-	os.Setenv("CGO_LDFLAGS", strings.Join(combinedLdFlags, " "))
+
+	// Write linker flags to a temporary file instead of pasing via env variable.
```
Comment (fmeum) [inline go/tools/builders/cgo2.go]: Could we do this only when ldflags are actually long? Response files are only supported in Go 1.23 and up and I would like to avoid breaking users on older versions of Go.

@jayconrod So far we've tried to support EOLed versions of Go, do you think we should keep doing that?

Comment (dgoel) [reply go/tools/builders/cgo2.go]: Looks like there's no portable API to query that. Windows seems to have the smallest value though. Are you okay if I hard code the check to 32,767?

https://learn.microsoft.com/en-us/windows/win32/procthread/environment-variables

Comment (fmeum) [reply go/tools/builders/cgo2.go]: Let's leave a small margin and go with 32,000.

Comment (dgoel) [reply go/tools/builders/cgo2.go]: Added. Please take a look.

**Review by fmeum — APPROVED** [review]

File: go/tools/builders/cgo2.go [hunk 2]
```diff
@@ -95,7 +98,27 @@ func cgo2(goenv *env, goSrcs, cgoSrcs, cSrcs, cxxSrcs, objcSrcs, objcxxSrcs, sSr
...
+
+	var ldflagsFile *os.File
+	combinedLdFlagsStr := strings.Join(combinedLdFlags, " ")
+	if len(combinedLdFlagsStr) < maxEnvVarSize {
+		os.Setenv("CGO_LDFLAGS", combinedLdFlagsStr)
+	} else {
+		// Write linker flags to a temporary file instead of pasing via env variable.
+		// This avoids "argument list too long" error with extremely large CGO_LDFLAGS
+		// that can exceed system limits.
+		ldflagsFile, err = os.Create(filepath.Join(workDir, "cgo-ldflags.txt"))
```
Comment (jayconrod) [inline go/tools/builders/cgo2.go]: Create a temporary file for this with `os.CreateTemp`. Make sure to delete it with a `defer` call.

File: go/tools/builders/cgo2.go [hunk 3]
```diff
@@ -95,7 +98,27 @@ func cgo2(goenv *env, goSrcs, cgoSrcs, cSrcs, cxxSrcs, objcSrcs, objcxxSrcs, sSr
 		}
 	}
 	combinedLdFlags = append(combinedLdFlags, defaultLdFlags()...)
-	os.Setenv("CGO_LDFLAGS", strings.Join(combinedLdFlags, " "))
+
+	var ldflagsFile *os.File
+	combinedLdFlagsStr := strings.Join(combinedLdFlags, " ")
+	if len(combinedLdFlagsStr) < maxEnvVarSize {
```
Comment (jayconrod) [inline go/tools/builders/cgo2.go]: Let's also check here whether this is Go 1.23 or higher. There are a few calls to `runtime.Version()` in this directory that check. The `onVersion` function in `link.go` is probably the most general.

**Comment by jayconrod** [comment]
Also, needs a test in `tests/core/cgo`. Just a buildable target that will trigger this functionality to make sure it still links.

**Comment by jayconrod** [comment]
> So far we've tried to support EOLed versions of Go, do you think we should keep doing that?

I think we can keep supporting them as long as it's convenient. In this case, we can gate the new functionality on `runtime.Version`.

File: go/tools/builders/cgo2.go (hunk 3 above)
Comment (dgoel) [reply go/tools/builders/cgo2.go]: I thought about this some more.

I think it's better to have a simple check based on version and not on the length of ldflags. This would prevent any future breakage if/when go drops the usage of `CGO_LDFLAGS` entirely. See code comments here:
https://go-review.googlesource.com/c/go/+/596615

Anyways, I updated the code. Please take a look.

**Comment by dgoel** [comment]
> Also, needs a test in `tests/core/cgo`. Just a buildable target that will trigger this functionality to make sure it still links.

Added a new test though some cgo existing tests were also sufficient.

File: tests/core/cgo/BUILD.bazel [hunk 4]
```diff
@@ -331,6 +332,38 @@ go_binary(
...
+MANY_EXT_LDFLAGS = [
+    flag
+    for i in range(5)
+    for flag in [
+        "-extldflags",
+        "-Wl,-rpath,$$ORIGIN/path/to/lib/{}".format(i),
+    ]
+]
+
+go_binary(
```
Comment (jayconrod) [inline tests/core/cgo/BUILD.bazel:343]: Is there a way to write this so the test is not Linux-specific? The current test uses Bash and assumes ELF.

Ideally, we'd have a `go_test` that includes a `.cc` file (and so is cgo). The `-extldflags` would be long enough to exceed the 32k limit but also observable in some way to the Go part of the test.

Not sure if `-rpath` will work for this. Is there something equivalent to Go's `-X` flag we could use?

If this isn't possible, I'd still be happy with just a `go_binary` with long enough flags to exceed the limit: we'd just be checking that it builds successfully.

Comment (dgoel) [reply tests/core/cgo/BUILD.bazel:343]: > Is there a way to write this so the test is not Linux-specific? The current test uses Bash and assumes ELF.

I don't know tbh.

> Ideally, we'd have a go_test that includes a .cc file (and so is cgo). The -extldflags would be long enough to exceed the 32k limit but also observable in some way to the Go part of the test.

I bumped up the size of ldflags (ideally, we want to set it to exceed the limit set in CI/CD runner). I didn't want to use a large size initially because of fear of breaking the tests for go 1.22. But looks like `rules_go` is tested with go 1.23+.

Ideally, we should have a build matrix that tests against different go versions, and some tests may get enabled/disabled given the version.

> Not sure if -rpath will work for this. Is there something equivalent to Go's -X flag we could use?

I did play around with setting values via linker flags and checking for those in a test (published in the latest commit). I am not sure how useful it is given that it is actually *not* passed as cgo_ldflags:
```
-B/usr/bin -Wl,-no-as-needed -Wl,-z,relro,-z,now -pass-exit-codes -Wl,--push-state,-as-needed -lstdc++ -Wl,--pop-state -Wl,--push-state,-as-needed -lm -Wl,--pop-state -pthread
```

> If this isn't possible, I'd still be happy with just a go_binary with long enough flags to exceed the limit: we'd just be checking that it builds successfully.

Frankly speaking, a lot of existing tests verify that cgo ldflags are propagated correctly. If they are not, build fails with linking errors (I verified this by not setting cgo flags). So checking that build succeeds is a solid confirmation that things are set up correctly.

Comment (jayconrod) [reply tests/core/cgo/BUILD.bazel:343]: > I did play around with setting values via linker flags and checking for those in a test (published in the latest commit). I am not sure how useful it is given that it is actually not passed as cgo_ldflags:

What I meant was: is there some C++ equivalent of Go's -X flag, where we can pass it in via `cgo_ldflags`, then observe its effect within the test binary without needing to examine the ELF. `-rpath` does has an observable effect, but I think it's different for ELF, machO, and PE. I don't remember the details though.

> Frankly speaking, a lot of existing tests verify that cgo ldflags are propagated correctly. If they are not, build fails with linking errors (I verified this by not setting cgo flags). So checking that build succeeds is a solid confirmation that things are set up correctly.

Fair enough. If there's not something easily available, let's just make this a `go_binary` and leave it at that. I mainly want to avoid the Linux-specific `target_compatible_with` and the Bash script.

Comment (dgoel) [reply tests/core/cgo/BUILD.bazel:343]: Trying to understand the ask here.

Are you suggesting that I drop both these tests?
- `sh_test` since it's Linux-specific.
- `cgo_ldflags_test` `go_test` since the linker values are passed via cgo flags.

And just keep `binary_with_rpath` `go_binary`?

Comment (jayconrod) [reply tests/core/cgo/BUILD.bazel:343]: Yes. So we're only testing that the binary can be built successfully, which `bazel build //...` does implicitly.

Ideally, we'd be able to run that binary as a test and have it verify the flags were actually passed in, but it doesn't seem like there's an easy, platform neutral way to do that.

Comment (dgoel) [reply tests/core/cgo/BUILD.bazel:343]: Done!

**Comment by jayconrod** [comment]
The change looks good to me. However, CI is failing on Windows due to the command-line length limit.

It looks like we're getting the Go version out of `go.mod` where we have `go 1.22.0` and `toolchain go1.23.6`. So I'd guess we're actually building with standard library version `1.22.0`, disabling this new feature. @fmeum Do you know if we support the `toolchain` directive? I'm not all that familiar with it, but it seems like that should control the version of the compiler and standard library we download, if it's higher than the `go` version.

**Comment by dgoel** [comment]
> The change looks good to me. However, CI is failing on Windows due to the command-line length limit.

My hunch is that the new cgo plumbing is working correctly (because cgo execution is not failing). The error is happening in the hand-off from cgo to the windows compiler where arguments are being passed via command line vs params/response file. That seems unrelated to this specific change.

In the latest commit, I restricted the test target to macos and linux. We can relax it if we are able to find and fix the underlying issue.

**Comment by fmeum** [comment]
@jayconrod We should be preferring `toolchain` over `go` for the SDK version as per https://github.com/bazel-contrib/rules_go/blob/98940c33e64548d13314a372bdc0103732407dc3/go/private/go_mod.bzl#L61.

**Comment by jayconrod** [comment]
So then @dgoel may be right that there is a problem between cgo and the Windows compiler. I don't like that we're disabling the test on Windows, but if that's true, then it can't work on Windows.

Unfortunately I don't have more bandwidth this week to confirm this. Let's merge this now.

**Comment by dgoel** [comment]
@fmeum could you enable squash + automerge for this PR if you are okay with the final set of changes?

**Review by fmeum — APPROVED** [review]

**Comment by dgoel** [comment]
Thanks @fmeum!

Would it be possible to push a new release to bcr?
